/**
 * SathiReliefRecommendation
 * ─────────────────────────────────────────────────────────────────────────────
 * Stores the relief suggestions presented to the user for a specific symptom
 * log day.  Returned by the Python AI service or generated by the rule engine
 * in the Node backend.  Linked 1-to-1 with SathiSymptomLog.
 *
 * Relationship:  SathiSymptomLog  1 ──► 1  SathiReliefRecommendation
 *                User             1 ──► N  SathiReliefRecommendation  (history)
 *
 * The relief items array mirrors what the Sathi UI renders in the
 * "Relief Suggestions" card so history browsing is trivial.
 */

import mongoose from 'mongoose';

// ── Individual recommendation item sub-schema ─────────────────────────────────
const reliefItemSchema = new mongoose.Schema(
  {
    // Category displayed in the UI card
    type: {
      type: String,
      enum: ['medicine', 'therapy', 'lifestyle', 'diet', 'supplement'],
      required: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
      maxlength: 120,
    },
    description: {
      type: String,
      trim: true,
      maxlength: 400,
    },
    // Lucide icon key for the frontend icon map (e.g. "pill", "flame", "leaf")
    icon: {
      type: String,
      default: 'heart',
    },
    // If this recommendation links to a medicine in the platform catalogue
    medicineId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Medicine',
      default: null,
    },
    medicineName: {
      type: String,
      trim: true,
      default: null,
    },
    // Confidence from AI for this specific item, 0–1
    confidence: {
      type: Number,
      min: 0,
      max: 1,
      default: null,
    },
    // Did the user mark this item as helpful?
    markedHelpful: {
      type: Boolean,
      default: null,   // null = no feedback yet
    },
  },
  { _id: false },
);

// ── Main schema ───────────────────────────────────────────────────────────────
const sathiReliefRecommendationSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    symptomLogId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'SathiSymptomLog',
      required: true,
      unique: true,   // strictly one recommendation set per daily log
      index: true,
    },
    healthProfileId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'SathiHealthProfile',
      required: true,
    },
    // Snapshot of the symptoms that triggered these recommendations
    // (denormalised so history is readable without joining SathiSymptomLog)
    triggerSymptoms: {
      type: [String],
      default: [],
    },
    // Date of the symptom log (midnight UTC)
    logDate: {
      type: Date,
      required: true,
      index: true,
    },

    // ── Recommendation items ───────────────────────────────────────────────
    recommendations: {
      type: [reliefItemSchema],
      validate: {
        validator: (arr) => arr.length <= 10,
        message: 'Maximum 10 relief items per log',
      },
    },
    recommendationCount: {
      type: Number,
      default: 0,
    },

    // ── Generation metadata ───────────────────────────────────────────────
    source: {
      type: String,
      enum: ['gemini', 'rule_based', 'hybrid', 'manual'],
      default: 'rule_based',
    },
    aiModel: {
      type: String,
      default: null,
    },
    generationLatencyMs: {
      // Useful for monitoring Python service performance
      type: Number,
      default: null,
    },
    // Full raw AI response stored for re-generation / debugging
    rawAiPayload: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
      select: false,
    },

    // ── User engagement ────────────────────────────────────────────────────
    viewedAt: {
      type: Date,
      default: null,
    },
    // Overall user rating for this set of suggestions
    overallRating: {
      type: Number,
      enum: [1, 2, 3, 4, 5, null],
      default: null,
    },
  },
  { timestamps: true },
);

// ── Indexes ───────────────────────────────────────────────────────────────────
sathiReliefRecommendationSchema.index({ userId: 1, logDate: -1 });   // history feed
sathiReliefRecommendationSchema.index({ userId: 1, createdAt: -1 });

// ── Pre-save ──────────────────────────────────────────────────────────────────
sathiReliefRecommendationSchema.pre('save', function (next) {
  this.recommendationCount = this.recommendations.length;
  next();
});

const SathiReliefRecommendation = mongoose.model(
  'SathiReliefRecommendation',
  sathiReliefRecommendationSchema,
);

export default SathiReliefRecommendation;
